services:
  - type: web
    name: Ankit Shakya Txt Bot2
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    repo: https://github.com/AnkitShakya95/TXT-TGBOT2
    branch: main
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: WEBHOOK
        sync: false
      - key: PORT
        sync: false  # Default port value, update if needed￼Enter
